services:
  pavlovarecipes:
    build: 
      context: ./Frontend/
      args:
        VITE_API_BASE_URL: "http://192.168.68.116:8000/app/"
    networks: 
      - app-network
    environment:
      - VITE_API_BASE_URL=http://192.168.68.116:8000/app/
    ports: 
      - "14165:3000"
  pavlovackend:
    networks: 
      - app-network
    build: ./Backend/
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - media_data:/app/media 
      - db_backup:/app/backups
  db:
    networks: 
    - app-network
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'pavlovadb'
      MYSQL_ROOT_PASSWORD: password

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  db_backup:
  media_data: