# Generated by Django 5.2.15 on 2026-06-19 08:38

import apps.core.filters
import django.contrib.postgres.indexes
from django.db import migrations
from apps.core.filters import Unaccent


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profilepicture'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='user',
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(Unaccent('username'), name='gin_trgm_ops'),
                        name='user_unaccent_trgm_idx'
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE INDEX user_unaccent_trgm_idx 
                    ON users_user 
                    USING gin (immutable_unaccent(username) gin_trgm_ops);
                    """,
                    reverse_sql="DROP INDEX IF EXISTS user_unaccent_trgm_idx;"
                ),
            ]
        ),
    ]
