# Generated by Django 5.2.15 on 2026-07-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_admin_fields', 'Can view admin-only user fields')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
