# Generated by Django 5.2.15 on 2026-07-22 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePictureJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=155)),
                ('worker', models.CharField(blank=True, default='', help_text='Hostname del worker que procesó el job.', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, help_text='Momento en que el worker tomó el job (status → processing).', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Momento en que el job terminó, sea éxito o fallo.', null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Duración del procesamiento en milisegundos. ', null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Número de reintentos realizados por Celery.')),
                ('error_msg', models.TextField(blank=True, default='', help_text='Detalle del error si status=FAILED.')),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original', models.ImageField(upload_to='profile_pictures/originals/')),
            ],
            options={
                'verbose_name': 'Profile Picture Job',
                'verbose_name_plural': 'Profile Picture Jobs',
            },
        ),
        migrations.AlterModelOptions(
            name='profilepicture',
            options={'verbose_name': 'Profile Picture', 'verbose_name_plural': 'Profile Pictures'},
        ),
        migrations.RemoveConstraint(
            model_name='profilepicture',
            name='unique_active_profile_picture',
        ),
        migrations.RemoveIndex(
            model_name='profilepicture',
            name='profile_picture_status_idx',
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='trace_id',
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='profilepicturejob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='profilepicturejob',
            index=models.Index(fields=['user', 'status'], name='profile_pictur_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='profilepicturejob',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'processing'])), fields=['user'], name='profile_picture_job_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilepicturejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing'])), fields=('user',), name='unique_active_profile_picture_job'),
        ),
    ]
