# Generated by Django 5.2.15 on 2026-07-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profilepicture_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailchangerequest',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'permissions': [('view_admin_fields', 'Can view admin-only user fields')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
