# Generated by Django 5.2.15 on 2026-07-28 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_emailchangerequest_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'permissions': [('view_admin_fields', 'Can view admin-only user fields'), ('manage_user_groups', 'Can assign, remove, and manage user group memberships'), ('manage_staff_status', 'Can assign, remove, and manage user group memberships')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
