# Generated by Django 5.2.15 on 2026-06-19 08:04

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        TrigramExtension(),

        UnaccentExtension(),

        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION immutable_unaccent(text)
            RETURNS text AS $$
            SELECT public.unaccent('public.unaccent', $1);
            $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS immutable_unaccent(text);"
        ),

    ]
