# Generated by Django 5.2.15 on 2026-07-29 04:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='group_images/')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_image', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Image',
                'verbose_name_plural': 'Group Images',
            },
        ),
        migrations.CreateModel(
            name='GroupMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_protected', models.BooleanField(default=False, help_text='Impide que usuarios sin privilegios asignen este grupo.')),
                ('description', models.TextField(blank=True, help_text='Descripción visible del grupo.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_metadata', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('groups_set', 'Grupos reemplazados (set)'), ('group_added', 'Grupo añadido'), ('group_removed', 'Grupo eliminado'), ('staff_changed', 'is_staff modificado'), ('super_changed', 'is_superuser modificado')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('before', models.JSONField(help_text='Estado antes del cambio.')),
                ('after', models.JSONField(help_text='Estado después del cambio.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contexto adicional: ip, user_agent, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='Usuario que realizó el cambio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_actions', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(help_text='Usuario sobre el que se realizó el cambio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorization Audit Log',
                'verbose_name_plural': 'Authorization Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target', '-created_at'], name='authlog_target_idx'), models.Index(fields=['actor', '-created_at'], name='authlog_actor_idx'), models.Index(fields=['change_type', '-created_at'], name='authlog_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupImageJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=155)),
                ('worker', models.CharField(blank=True, default='', help_text='Hostname del worker que procesó el job.', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, help_text='Momento en que el worker tomó el job (status → processing).', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Momento en que el job terminó, sea éxito o fallo.', null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Duración del procesamiento en milisegundos. ', null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Número de reintentos realizados por Celery.')),
                ('error_msg', models.TextField(blank=True, default='', help_text='Detalle del error si status=FAILED.')),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original', models.ImageField(upload_to='group_images/originals/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_image_jobs', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Image Job',
                'verbose_name_plural': 'Group Image Jobs',
                'indexes': [models.Index(fields=['group', 'status'], name='group_image_status_idx'), models.Index(condition=models.Q(('status__in', ['pending', 'processing'])), fields=['group'], name='group_image_job_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing'])), fields=('group',), name='unique_active_group_image_job')],
            },
        ),
    ]
