# Generated by Django 5.2.15 on 2026-08-11 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authorization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authorizationauditlog',
            name='authlog_target_idx',
        ),
        migrations.RemoveIndex(
            model_name='authorizationauditlog',
            name='authlog_type_idx',
        ),
        migrations.RemoveField(
            model_name='authorizationauditlog',
            name='target',
        ),
        migrations.AddField(
            model_name='authorizationauditlog',
            name='target_group',
            field=models.ForeignKey(blank=True, help_text='Grupo sobre el que se realizó el cambio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_group_changes', to='auth.group'),
        ),
        migrations.AddField(
            model_name='authorizationauditlog',
            name='target_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='authorizationauditlog',
            name='target_object_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='authorizationauditlog',
            name='target_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='authorizationauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Usuario sobre el que se realizó el cambio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_user_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorizationauditlog',
            name='change_type',
            field=models.CharField(choices=[('groups_set', 'Grupos reemplazados (set)'), ('group_added', 'Grupo añadido'), ('group_removed', 'Grupo eliminado'), ('staff_changed', 'is_staff modificado'), ('super_changed', 'is_superuser modificado'), ('group_created', 'Grupo creado'), ('group_updated', 'Grupo modificado'), ('group_protected', 'Protección de grupo alterada'), ('group_deleted', 'Grupo eliminado'), ('image_changed', 'Imagen del grupo modificada')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='authorizationauditlog',
            index=models.Index(fields=['target_user', '-created_at'], name='authlog_tgt_usr_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationauditlog',
            index=models.Index(fields=['target_group', '-created_at'], name='authlog_tgt_grp_idx'),
        ),
        migrations.AddConstraint(
            model_name='authorizationauditlog',
            constraint=models.CheckConstraint(condition=models.Q(('target_user__isnull', True), ('target_group__isnull', True), _connector='OR'), name='audit_target_not_both'),
        ),
    ]
