# Generated by Django 5.2.15 on 2026-07-23 22:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('grasas_saturadas', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('grasas_trans', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('grasas_insaturadas', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sodio', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('consistencia', models.CharField(choices=[('liquido', 'Líquido'), ('solido', 'Sólido')], default='liquido', max_length=10)),
                ('tipo', models.CharField(choices=[('personal', 'Personal'), ('global', 'Global')], default='personal', max_length=10)),
                ('escala_agua', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PorcionIngrediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porciones', to='ingredients.ingrediente')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'global')), fields=('nombre',), name='unique_ingrediente_global'),
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'personal')), fields=('nombre', 'creador'), name='unique_ingrediente_personal_usuario'),
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('creador__isnull', True), ('tipo', 'global')), models.Q(('creador__isnull', False), ('tipo', 'personal')), _connector='OR'), name='ingrediente_tipo_creador_consistente'),
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.CheckConstraint(condition=models.Q(('escala_agua__gte', Decimal('0.0')), ('escala_agua__lte', Decimal('5.0'))), name='escala_agua_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.CheckConstraint(condition=models.Q(('calorias__gte', Decimal('0.00')), ('carbohidratos__gte', Decimal('0.00')), ('grasas_insaturadas__gte', Decimal('0.00')), ('grasas_saturadas__gte', Decimal('0.00')), ('grasas_trans__gte', Decimal('0.00')), ('proteinas__gte', Decimal('0.00')), ('sodio__gte', Decimal('0.00'))), name='nutrientes_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='porcioningrediente',
            constraint=models.UniqueConstraint(fields=('ingrediente', 'nombre'), name='unique_nombre_porcion_ingrediente'),
        ),
    ]
