# Generated by Django 5.2.15 on 2026-07-24 22:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='ingredient_images/')),
            ],
            options={
                'verbose_name': 'Ingredient Image',
                'verbose_name_plural': 'Ingredient Images',
            },
        ),
        migrations.CreateModel(
            name='IngredientImageJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=155)),
                ('worker', models.CharField(blank=True, default='', help_text='Hostname del worker que procesó el job.', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, help_text='Momento en que el worker tomó el job (status → processing).', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Momento en que el job terminó, sea éxito o fallo.', null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Duración del procesamiento en milisegundos. ', null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Número de reintentos realizados por Celery.')),
                ('error_msg', models.TextField(blank=True, default='', help_text='Detalle del error si status=FAILED.')),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original', models.ImageField(upload_to='ingredient_images/originals/')),
            ],
            options={
                'verbose_name': 'Ingredient Image Job',
                'verbose_name_plural': 'Ingredient Image Jobs',
            },
        ),
        migrations.AddField(
            model_name='porcioningrediente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porcioningrediente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='porcioningrediente',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', Decimal('0.00'))), name='porcion_cantidad_positiva'),
        ),
        migrations.AddField(
            model_name='ingredientimage',
            name='ingrediente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_image', to='ingredients.ingrediente'),
        ),
        migrations.AddField(
            model_name='ingredientimagejob',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_image_jobs', to='ingredients.ingrediente'),
        ),
        migrations.AddIndex(
            model_name='ingredientimagejob',
            index=models.Index(fields=['ingrediente', 'status'], name='ingredient_image_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientimagejob',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'processing'])), fields=['ingrediente'], name='ingredient_img_job_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingredientimagejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing'])), fields=('ingrediente',), name='unique_active_ingredient_image_job'),
        ),
    ]
