# Generated by Django 5.2.15 on 2026-07-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredientimage_ingredientimagejob_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'ordering': ['-id'], 'permissions': [('manage_global_ingredients', 'Can create, update and delete global ingredients')]},
        ),
    ]
