# Generated by Django 5.1.5 on 2025-02-16 06:13

import app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('about', models.TextField(blank=True, default='')),
                ('profile_picture', models.ImageField(default='images/user-icon.png', upload_to='images/')),
                ('social_youtube', models.URLField(blank=True, default='')),
                ('social_facebook', models.URLField(blank=True, default='')),
                ('social_twitter', models.URLField(blank=True, default='')),
                ('groups', models.ManyToManyField(blank=True, related_name='app_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='app_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', app.models.CustomUserManager()),
            ],
        ),
    ]
