# Generated by Django 5.1.5 on 2025-02-28 06:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/user-icon.webp', upload_to=app.models.UniqueImagePath()),
        ),
    ]
