# Generated by Django 5.1.5 on 2025-03-23 05:16

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_emailverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('carbohidratos', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('grasas_saturadas', models.FloatField()),
                ('grasas_trans', models.FloatField()),
                ('grasas_insaturadas', models.FloatField()),
                ('sodio', models.FloatField()),
                ('foto_ingrediente', models.ImageField(default='ingredientes/ingrediente_placeholder.webp', upload_to=app.models.UniqueImagePath())),
                ('tipo', models.CharField(choices=[('personal', 'Personal'), ('global', 'Global')], default='personal', max_length=10)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'tipo', 'creador'), name='unique_ingrediente_personal_usuario'), models.UniqueConstraint(condition=models.Q(('tipo', 'global')), fields=('nombre', 'tipo'), name='unique_ingrediente_global')],
            },
        ),
    ]
