# Generated by Django 5.1.5 on 2025-03-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ingrediente'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingrediente',
            name='unique_ingrediente_personal_usuario',
        ),
        migrations.RemoveConstraint(
            model_name='ingrediente',
            name='unique_ingrediente_global',
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'global')), fields=('nombre',), name='unique_ingrediente_global'),
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'personal')), fields=('nombre', 'creador'), name='unique_ingrediente_personal_usuario'),
        ),
    ]
