# Generated by Django 5.1.5 on 2025-03-25 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_ingrediente_unique_ingrediente_personal_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='ingrediente',
            name='unique_ingrediente_global',
        ),
        migrations.RemoveConstraint(
            model_name='ingrediente',
            name='unique_ingrediente_personal_usuario',
        ),
    ]
