# Generated by Django 5.1.5 on 2025-03-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_ingrediente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='consistencia',
            field=models.CharField(choices=[('liquido', 'Liquido'), ('solido', 'Solido')], default='liquido', max_length=10),
        ),
    ]
