# Generated by Django 5.1.5 on 2025-03-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ingrediente_consistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='calorias',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
