# Generated by Django 5.1.5 on 2025-04-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_categoria_etiqueta_receta_comentario_recetafavorito_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recetafavorito',
            unique_together={('receta', 'usuario')},
        ),
    ]
