# Generated by Django 5.1.5 on 2025-04-19 03:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_recetafavorito_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto_categoria',
            field=models.ImageField(default='categorias/categoria_placeholder.webp', upload_to=app.models.UniqueImagePath()),
        ),
    ]
