# Generated by Django 5.1.5 on 2025-05-29 00:49

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_categoria_foto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='foto_receta',
            field=models.ImageField(default='recetas/receta_placeholder.webp', upload_to=app.models.UniqueImagePath()),
        ),
    ]
