# Generated by Django 5.1.5 on 2025-06-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_receta_categoria_alter_receta_foto_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='rating',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='puntuacion',
            field=models.FloatField(default=0.0),
        ),
    ]
