# Generated by Django 5.1.5 on 2025-06-20 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_receta_rating_alter_comentario_puntuacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comentario',
            unique_together={('receta', 'usuario')},
        ),
        migrations.CreateModel(
            name='PlanAlimenticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('objetivo_calorias', models.IntegerField(default=2000)),
                ('objetivo_proteinas', models.IntegerField(default=50)),
                ('objetivo_carbohidratos', models.IntegerField(default=275)),
                ('objetivo_grasas_saturadas', models.IntegerField(default=20)),
                ('objetivo_grasas_insaturadas', models.IntegerField(default=44)),
                ('objetivo_grasas_trans', models.IntegerField(default=2)),
                ('objetivo_sodio', models.IntegerField(default=2300)),
                ('personas', models.IntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_alimenticios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAlimenticioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('plan_alimenticio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='app.planalimenticio')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAlimenticioDiaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcion', models.FloatField(default=1.0)),
                ('plan_alimenticio_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='app.planalimenticiodia')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_alimenticio_recetas', to='app.receta')),
            ],
        ),
    ]
