# Generated by Django 5.1.5 on 2025-06-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_comentario_unique_together_planalimenticio_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planalimenticio',
            constraint=models.UniqueConstraint(fields=('usuario',), name='unique_plan_alimenticio_usuario'),
        ),
    ]
