# Generated by Django 5.1.5 on 2025-07-16 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_objetivosai_promediocalorias_ingrediente_escala_agua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='puntuacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
