# Generated by Django 5.1.5 on 2026-05-13 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_receta_puntuacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpcionPersonalizadaIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cantidad", models.FloatField()),
                (
                    "ingrediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opcionPersonalizadaIngrediente",
                        to="app.ingrediente",
                    ),
                ),
            ],
        ),
    ]
